config/routes.rb
Rails.application.routes.draw do

  root 'access#landing'
  
  get 'login', to: "access#login", as: 'login'

  get 'signup', to: "access#signup", as: 'signup'

  post 'login', to: "access#attempt_login"

  post 'signup', to: "access#create"

  # get 'home', to: "access#home", as: 'home'

  get 'logout', to: "access#logout"

  get '/forgot' => 'access#forgot_password'
  post '/send_reset' => 'access#send_reset'
  get '/reset/:token' => 'access#reset_password'
  post '/update_password' => 'access#update_password'


  resources :categories

  resources :photos do
    resources :orders
  end

  resources :users, except: [:create, :new] do
    resources :photos
  end

  get 'home', to: "photos#all", as: 'all_photos'
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  #before_action :confirm_logged_in, only: [:home]
  before_action :prevent_login_signup, only: [:signup, :login, :landing, :all]


  def landing

  end

  def login
    
  end

  def signup
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You are now logged in!"
      UserMailer.signup_confirmation(@user, root_url()).deliver
      redirect_to all_photos_path
    else
      render :signup
    end
   end

  def reset_password
    @token = params[:token]
    @user = User.find_by :reset_token => @token
    if @user.nil?
      flash[:error] = "Invalid reset token"
      render :login
    else  
      render :reset_password
    end
  end

  #post '/send_reset' => 'user#reset_password'
  def send_reset
    # username in param
    username = params[:username]
    user =  User.find_by username: username
    if user.nil?
      flash[:error] = "No such user:" + username
    else
      # create and save reset token on user
      user.reset_token = (0...16).map { (65 + rand(26)).chr }.join
      user.save
      UserMailer.forgot_password_email(user, root_url() ).deliver
      flash[:success] = "Please check your email for reset instructions ..."
    end
    render :forgot_password
  end

  def update_password
    user_params = params.permit(:username, :password, :password_confirmation)
    @user = User.find_by username: user_params[:username]
    @user.update_attributes(password: user_params[:password], password_confirmation: user_params[:password_confirmation])
    flash[:success] = "Your password has changed, try it out ..."
    render :login
  end

  def attempt_login

    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if !found_user
      flash.now[:alert] = "Invalid username"
      render :login

    elsif !authorized_user
      flash.now[:alert] = "Invalid password"
      render :login

    else
      session[:user_id] = authorized_user.id
      flash[:success] = "You are now logged in."
      redirect_to all_photos_path
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to login_path
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :username, :password, :password_digest)
  end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/forgot_password.html.erb
<h1>Forgot password?</h1>

<div class="row">
  <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
    <%= form_tag '/send_reset', :method=>'post' do %>

      <%= label_tag :username %>
      <%= text_field_tag :username %>

      <%= submit_tag "Reset", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/access/home.html.erb
<h2>Access#home</h2>

<h1>Welcome to our Website!</h1>

<%= link_to "Logout", logout_path, class:"btn btn-danger" %>

app/views/access/landing.html.erb
    <!-- Header -->
    <div class="intro-header">

        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h1>Project 2</h1>
                        <h3>Upload and License Your Photos on the Web</h3>
                        <hr class="intro-divider">
                        <ul class="list-inline intro-social-buttons">
                            <li>
                                <a href="#"class="btn btn-default btn-lg">Login</a>
                            </li>
                        </ul>
                    </div>
                    <div class="signup">
                    <h3>Don't have an account?  <a href="#"> SIGN UP!</a></h3>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

    <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">About the Artists</h2>
                    <p class="lead">Blah blah blah blah blah.  Blah blah blah, blah blah blah.
                    Blah blah blah blah.  Blah blah blah blah blah.  Blah blah blah, blah blah blah.
                    Blah blah blah blah.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="http://www.cultivatedwit.com/wp-content/uploads/2013/08/placeholder1.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">The Perks of Buying</h2>
                    <p class="lead">Blah blah blah blah blah.  Blah blah blah, blah blah blah.
                    Blah blah blah blah.  Blah blah blah blah blah.  Blah blah blah, blah blah blah.
                    Blah blah blah blah.</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="http://www.cultivatedwit.com/wp-content/uploads/2013/08/placeholder1.jpg" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <!-- <div class="content-section-a">

        <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
                    <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="img/phones.png" alt="">
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div> -->
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Join Us!</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Project 2 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

app/views/access/login.html.erb
<h1>Login</h1>

  <%= form_tag(login_path) do %>
<p>
  <%= label_tag(:username)%>
  <%= text_field_tag(:username, params[:username], autofocus: true)%>
</p>
<p>
  <%= label_tag(:password)%>
  <%= password_field_tag(:password)%>
</p>
<p>
  <%= submit_tag("Login", class: "btn btn-primary") %>
</p>
<% end %>

<%= link_to "Don't have an account? Sign up here", signup_path%>
<p>Forgot Password? <%= link_to "Reset!", forgot_path %></p>

app/views/access/reset_password.html.erb
<h1>Reset Password</h1>
<div class="row">
  <div class="col-md-6 col-sm-6 col-md-offset-3 col-sm-offset-3">
    
  <%= form_tag(update_password_path, :method=>'post') do %>

    <p>
      <%= text_field_tag(:username, @user.username, readonly: true) %>
    </p>
      
    <p>
   <%= label_tag(:password, "New Password") %> 
   <%= password_field_tag :password %>
   </p>

   <p>
      <%= label_tag(:password_confirmation, "Confirmation") %> 
      <%= password_field_tag :password_confirmation %>
   </p>

    <p>
     <%= submit_tag 'Reset Password', class: "btn btn-large btn-primary" %>
    </p>
  <% end %>

  </div>
</div>

app/views/access/signup.html.erb
<h1>Signup</h1>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <p class = "text-danger"><%= error %></p>
  <% end %>
<% end %>

<%= form_for(@user, url: signup_path) do |f|%>

<p>
  <%= f.label(:first_name) %>
  <%= f.text_field(:firstname, autofocus: true) %>
</p>
<p>
  <%= f.label(:last_name) %>
  <%= f.text_field(:lastname) %>
</p>
<p>
  <%= f.label(:email) %>
  <%= f.text_field(:email) %>
</p>
<p>
  <%= f.label(:username) %>
  <%= f.text_field(:username) %>
</p>
<p>
  <%= f.label(:password) %>
  <%= f.password_field(:password) %>
</p>
<p>
  <%= f.submit("Signup", class: "btn btn-primary") %>
</p>
  <%= link_to "Have an account already? Login here", login_path %>
<% end %>