config/routes.rb
Rails.application.routes.draw do

  root 'access#landing'
  
  get 'login', to: "access#login", as: 'login'

  get 'signup', to: "access#signup", as: 'signup'

  post 'login', to: "access#attempt_login"

  post 'signup', to: "access#create"

  # get 'home', to: "access#home", as: 'home'

  get 'logout', to: "access#logout"

  get '/forgot' => 'access#forgot_password'
  post '/send_reset' => 'access#send_reset'
  get '/reset/:token' => 'access#reset_password'
  post '/update_password' => 'access#update_password'


  resources :categories

  resources :photos do
    resources :orders
  end

  resources :users, except: [:create, :new] do
    resources :photos
  end

  get 'home', to: "photos#all", as: 'all_photos'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	has_many :category_photos
	has_many :categories, through: :category_photos
	belongs_to :user

	validates :title,
		presence: true
	validates :url,
		presence: true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :check_user, only: [:edit]
	before_action :current_user, except: [:all]
  before_action :categories, only: [:new, :create, :show, :edit, :update]
	before_action :confirm_logged_in, only: [:new, :create, :edit, :show, :index]
  


  def index
    @photos = @current_user.photos
  end


  def all
    #binding.pry
    @portraits = Category.find(1).photos
    @bw = Category.find(2).photos
    @landscape = Category.find(3).photos
    @abstract = Category.find(4).photos
    #binding.pry
  end

  def new
  	@photo = @current_user.photos.new
  end

  def create
    @photo = @current_user.photos.create(photo_params)
    params[:photo][:categories] ||= []
    @photo.categories = []
    @photo.categories << Category.find(params[:photo][:categories])
    if @photo.save
      # split the url 
      # make an api call with HTTParty to get json hash
      # save the width and height to the DB
      photo_meta_data = HTTParty.get("#{@photo.url}-/json/")
      @photo.update_attributes(width: photo_meta_data["width"], height: photo_meta_data["height"])

      flash[:success] = "Photo created"
      redirect_to user_photo_path(@current_user, @photo.id)
    else
      render :new
    end
  end

  def edit
  	@photo = Photo.find(params[:id])
  end

  def show
  	@photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    @photo.update_attributes(photo_params)
    params[:photo][:categories] ||= []
    @photo.categories = []
    @photo.categories << Category.find(params[:photo][:categories])
    if @photo.save
      flash[:success] = "Photo successfully updated"
      redirect_to user_photo_path(@current_user, @photo.id)
    else
      render :edit
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    flash[:success] = "Photo deleted"
    redirect_to user_photos_path(@current_user)
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :url, :price, :user_id)
  end

  def categories
    @categories = Category.all
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/all.html.erb
<div role="tabpanel">
  <ul class="nav nav-tabs" role="tablist" id="myTab">
    <li role="presentation" class="active"><a href="#portrait" aria-controls="portrait" role="tab" data-toggle="tab">Portrait</a></li>
    <li role="presentation"><a href="#bw" aria-controls="bw" role="tab" data-toggle="tab">Black and White</a></li>
    <li role="presentation"><a href="#landscape" aria-controls="landscape" role="tab" data-toggle="tab">Landscape</a></li>
    <li role="presentation"><a href="#abstract" aria-controls="abstract" role="tab" data-toggle="tab">Abstract</a></li>
  </ul>

  <div class="tab-content">








    <div role="tabpanel" class="tab-pane active fade" id="portrait">
      <% @portraits.each_with_index do |p, index| %>

        <% if index == 0 %>

          <div class="row text-center">
            <div class="col-sm-4">
              <%= image_tag("http://www.ucarecdn.com/85b5644f-e692-4855-9db0-8c5a83096e25/-/resize/200x/filename.jpg") %>
            </div>

        <% elsif index % 9 == 0 %>

          </div>

        <% elsif index % 3 == 0 %>

          </div>
          <div class="row text-center">
            <div class="col-sm-4">
              <%= image_tag("http://www.ucarecdn.com/85b5644f-e692-4855-9db0-8c5a83096e25/-/resize/200x/filename.jpg")%>
            </div>

        <% else %>

            <div class="col-sm-4">
              <%= image_tag("http://www.ucarecdn.com/85b5644f-e692-4855-9db0-8c5a83096e25/-/resize/200x/filename.jpg") %>
            </div>

        <% end %> 
      <% end %>

    </div>
    </div>

    <div role="tabpanel" class="tab-pane fade" id="bw">
      Two
    </div>
    <div role="tabpanel" class="tab-pane fade" id="landscape">three</div>
    <div role="tabpanel" class="tab-pane fade" id="abstract">four</div>
  </div>
</div>




<script>
  $(function () {
    $('#myTab a:last').tab('show')
  })
</script>

app/views/photos/edit.html.erb
<h1>Photos#edit</h1>


<h1>Edit a photo</h1>

<% if @photo.errors.any? %>
  <ul class = "text-danger list-style-none">
   <%  for err in @photo.errors.full_messages %>
    <li>
      <%= err%>
    </li>
    <% end %>
  </ul>
<% end %>

<%= simple_form_for([@current_user, @photo], method: "put", html: {class: 'form-horizontal' }) do |f| %>
<div class = "form-group">
  <%= f.input(:title, input_html: {maxlength: 50}, autofocus: true, class: "form-control") %>
</div>

<div class="form-group">
  <%= f.uploadcare_field :url, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.input(:price,  class: "form-control") %>
</div>

<div class="form-group">
  <% @categories.each do |c| %>
  <%= f.check_box(:categories, {checked: @photo.categories.include?(c), multiple: true}, c.id.to_i, nil) %>
  <%= c.name %>
  <% end %>
</div>
<%= f.button :submit, "Edit a photo!", class: "btn btn-lg btn-info" %>
<% end %>

app/views/photos/index.html.erb
<% @photos.each do |p| %>
	<li>
      <%= image_tag(p.url) %>
    </li>
<% end %>

app/views/photos/new.html.erb
<h1>Add a new photo</h1>

<% if @photo.errors.any? %>
  <ul class = "text-danger list-style-none">
   <%  for err in @photo.errors.full_messages %>
    <li>
      <%= err%>
    </li>
    <% end %>
  </ul>
<% end %>

<div class="jumbotron">
  <div class="signup">
    <%= simple_form_for([@current_user, @photo], html: {class: 'form-horizontal' }) do |f|%>
    <div class="form-group">
      <%= f.input(:title, autofocus: true, class: 'form-control') %>
    </div>

    <div class="form-group">
      <%= f.uploadcare_field (:url) %>
    </div>

    <div class="form-group">
      <%= f.input(:price) %>
    </div>

    <div class="form-group">
      <p id="tags">Tags:</p>
      <% @categories.each do |c| %>
      <%= f.check_box(:categories, {checked: @photo.categories.include?(c), multiple: true}, c.id.to_i, nil) %>
      <%= c.name %>
      <% end %>
    </div>

    <%= f.button :submit, "Add a photo!", class: "btn btn-lg btn-info" %>
    <% end %>
  </div>

</div>

app/views/photos/show.html.erb
<div class="container">
	<div class="row">
		
		<div class="col-md-12 pic">
			<%= image_tag("#{@photo.url}-/resize/x700/") %>
		</div>
		</div>
	</div>
<div class="jumbotron">
<div class="row">
<div class="col-md-4">
	<h4>Title: <%= @photo.title %></h4>
	<h4>
		Price: <%= @photo.price %>
	</h4>
</div>
<div class="col-md-4">
	<h4>
		Tags: 
		<% @photo.categories.each do |c| %>
		<li><small><%= c.name %></small></li>
		<% end %>
	</h4>
	</div>
	<div class="col-md-4">
		<% if @current_user.id == params[:user_id].to_i %>
		<%= link_to(" Edit ", edit_user_photo_path(@current_user, @photo), class: "btn btn-info pull-right edit-button") %>
		<br>
		<br>
		<%= link_to 'Delete',  user_photo_path(@current_user, @photo.id),  method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info pull-right" %>
		<% end %>
		<% if @current_user.id != params[:user_id].to_i %>
		<%= link_to("Purchase", new_photo_order_path(@current_user, @photo.id), class: "btn btn-info pull-right") %>
		<% end %>
	</div>
</div>