config/routes.rb
Rails.application.routes.draw do

  root 'access#landing'
  
  get 'login', to: "access#login", as: 'login'

  get 'signup', to: "access#signup", as: 'signup'

  post 'login', to: "access#attempt_login"

  post 'signup', to: "access#create"

  # get 'home', to: "access#home", as: 'home'

  get 'logout', to: "access#logout"

  get '/forgot' => 'access#forgot_password'
  post '/send_reset' => 'access#send_reset'
  get '/reset/:token' => 'access#reset_password'
  post '/update_password' => 'access#update_password'


  resources :categories

  resources :photos do
    resources :orders
  end

  resources :users, except: [:create, :new] do
    resources :photos
  end

  get 'home', to: "photos#all", as: 'all_photos'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://ucarecdn.com/widget/1.0.1/uploadcare/uploadcare-1.0.1.min.js"></script>
  <%= uploadcare_settings %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="<%= root_path %>">Project 2</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <a href="<%= all_photos_path %>">Explore</a>
                  </li>
                  <% if session[:user_id] %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Settings</a></li>
                        <li><a href="#">Orders</a></li>
                      </ul>
                    </li>
                    <li>
                      <a href="<%= logout_path %>">Logout</a>
                    </li>
                  <% end %>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>

  <% flash.each do |key, value| %>
    <% if key == "notice" %>
      <%= content_tag :div, value, class: "text-center alert alert-warning" %>
    <% elsif key == "alert" %>
      <%= content_tag :div, value, class: "text-center alert alert-danger" %>
    <% else %>
      <%= content_tag :div, value, class: "text-center alert alert-success" %>
    <% end %>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
  
</body>
</html>